# https://travis-ci.org/#!/translate/pootle
language: python
python:
  - 2.5
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
install:
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - pip install -r requirements/base.txt --use-mirrors
script:
  - ./manage.py collectstatic --noinput
  - ./manage.py assets build
  - ./setup.py build_mo
  - ./manage.py runserver
notifications:
  email:
    on_failure: change
    on_success: change
