# https://travis-ci.org/#!/translate/pootle
language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements/build.txt --timeout=240
  - pip freeze  # Print all installed versions for reference.
script:
  - make build SHELL=/bin/bash TAIL='|tail -40; exit $$PIPESTATUS'
  - ./manage.py runserver &
  - TESTPID=$!
  - sleep 100
  - kill -2 $TESTPID
notifications:
  email:
    on_failure: always
    on_success: change
