# https://travis-ci.org/#!/translate/pootle
language: python
python:
  - 2.6
  - 2.7
env:
  matrix:
    - DJANGO_VERSION=1.6.5 DATABASE_BACKEND=sqlite
    - DJANGO_VERSION=1.6.5 DATABASE_BACKEND=postgres
    - DJANGO_VERSION=1.6.5 DATABASE_BACKEND=mysql
    - DJANGO_VERSION=1.7.1 DATABASE_BACKEND=sqlite
    - DJANGO_VERSION=1.7.1 DATABASE_BACKEND=postgres
    - DJANGO_VERSION=1.7.1 DATABASE_BACKEND=mysql
matrix:
  exclude:
    - python: 2.6
      env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=sqlite
    - python: 2.6
      env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=mysql
    - python: 2.6
      env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=postgres
  allow_failures:
    # Allow failure on Django 1.7.1 until we've migrated away from South to
    # Django migration
    - env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=sqlite
    - env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=mysql
    - env: DJANGO_VERSION=1.7.1 DATABASE_BACKEND=postgres
cache:
  - apt
before_install:
  - travis_retry sudo apt-get install -qq bc
install:
  - travis_retry pip install -r requirements/travis.txt --timeout=240
  - travis_retry pip install "Django>=$DJANGO_VERSION,<"$(echo $(echo $DJANGO_VERSION | cut -d"." -f1,2) + 0.1 | bc) --timeout=240
  - pip freeze  # Print all installed versions for reference.
before_script:
  - if [[ $DATABASE_BACKEND == 'postgres' ]]; then psql -c 'create database pootle;' -U postgres; fi
  - if [[ $DATABASE_BACKEND == 'mysql' ]]; then mysql -e 'create database pootle;'; fi
script:
  - python -m compileall -q -f .
  # FIXME revert breakdown of 'make build' after core merge
  #- make docs
  #- make build SHELL=/bin/bash TAIL='|tail -40; exit $$PIPESTATUS'
  # FIXME Don't raise Warning as Errors till docs have landed and are cleaned
  # up See https://github.com/translate/pootle/issues/3307
  - (cd docs; make SPHINXOPTS="-q" html)
  - make assets
  - make mo
  - coverage run --parallel-mode manage.py syncdb --noinput --traceback
  - coverage run --parallel-mode manage.py migrate --traceback
  - coverage run --parallel-mode manage.py initdb --traceback
  - coverage run --parallel-mode ./manage.py runserver --traceback &
  - TESTPID=$!
  - sleep 20
  - kill -2 $TESTPID
  - tests/version-migration/migrate.sh
  - make pep8
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    on_failure: always
    on_success: change
services:
  - memcached
