auto: true

name: Pootle
description: Online translation tool.
author: Translate House

about_url: http://translatehouse.org/about.html
docs_url: http://translate.readthedocs.org/projects/pootle/en/latest/
