auto: true

name: Pootle
description: Online translation tool.
latest_version: 2.1.6
author: Translate House

about_url: http://translatehouse.org/about.html
docs_url: http://translate.readthedocs.org/projects/pootle/en/latest/
gh_url: https://github.com/translate/pootle
