auto: true

name: Pootle
description: Online translation tool.
latest_version: 2.5.1.3
author: Translate House

about_url: http://translatehouse.org/about.html
docs_url: http://docs.translatehouse.org/projects/pootle/
gh_url: https://github.com/translate/pootle
contact_url: mailto:dev@translate.org.za
